name: release new version

on:
  workflow_dispatch:
  push:
    branches: [master]
    

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: checkout the source code
        uses: actions/checkout@v2

      - uses: ./.github/workflows/release
        with:
          tag_name: ${{ github.event.after }}
