name: release new version

on:
  workflow_dispatch:
  push:
    tags: ['*']

  release:
    steps:
      - uses: ./.github/workflows/release.yaml
        with:
          tag_name: ${{ github.event.after }}
