name: release new version

on:
  workflow_dispatch:
  push:
    tags: ['*']

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: ./.github/workflows/release.yaml
        with:
          tag_name: ${{ github.event.after }}
