# mostly from https://github.com/marketplace/actions/build-and-push-docker-images
jobs:
  docker:
    inputs:
      tag_name: 
        type: string
        require: true

    secrets: inherit

    runs-on: ubuntu-latest

    steps:
      - name: checkout the source code
        uses: actions/checkout@v2

      - name: set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: set up docker buildx
        uses: docker/setup-buildx-action@v1

      - name: login to registry
        uses: docker/login-action@v1
        with:
          registry: registry.office.lombrozo.net
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: djeebus/csi-sshfs:${{ inputs.tag_name }}
