name: release new version

on:
  workflow_dispatch:
  push:
    tags: ['*']

  release:
    steps:
      - name: Extract tag name
        id: tag
        run: echo ::set-output name=VERSION::$(echo $GITHUB_REF | cut -d / -f 3)

      - uses: ./.github/workflows/release.yaml
        with:
          tag_name: ${{ steps.tag.output.VERSION }}
