name: release new version

on:
  workflow_dispatch:
  push:
    tags: ['*']

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Extract tag name
        id: tag
        run: echo ::set-output name=VERSION::$(echo $GITHUB_REF | cut -d / -f 3)

      - name: checkout the source code
        uses: actions/checkout@v2

      - uses: ./.github/workflows/release
        with:
          tag_name: ${{ steps.tag.output.VERSION }}
