name: release new version

on:
  workflow_dispatch:
  push:
    tags: ['*']

jobs:
  release:
    runs-on: self-hosted

    steps:
      - name: checkout the source code
        uses: actions/checkout@v2

      - name: Extract tag name
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: login to registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: $${{ secrets.GITHUB_TOKEN }}

      - name: Build the hello-docker Docker image
        run: |
          docker build . --tag ghcr.io/djeebus/csi-sshfs:${{ env.RELEASE_VERSION }}
          docker push ghcr.io/djeebus/csi-sshfs:${{ env.RELEASE_VERSION }}
