name: release new version

on:
  workflow_dispatch:
  push:
    tags: ['*']

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: checkout the source code
        uses: actions/checkout@v2

      - name: Extract tag name
        id: tag
        run: echo ::set-output name=VERSION::$(echo $GITHUB_REF | cut -d / -f 3)

      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Test
        run: |
          echo "GITHUB_REF = $GITHUB_REF"
          echo "VERSION = $VERSION"
          echo "RELEASE_VERSION = $RELEASE_VERSION"
          echo "env.RELEASE_VERSION = ${{ env.RELEASE_VERSION }}"

      - name: set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: set up docker buildx
        uses: docker/setup-buildx-action@v1

      - name: login to registry
        uses: docker/login-action@v1
        with:
          registry: registry.thehideaway.social
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: registry.thehideaway.social/djeebus/csi-sshfs:${{ steps.tag.output.VERSION }}
